class LoanSanction {
  String somiteename,
      somiteeid,
      membername,
      memberid,
      memberphone,
      installmentfrequency,
      loanperiod,
      remarks,
      status,
      grantor1name,
      grantor2name,
      loanpurpose,
      grantor1id,
      grantor2id,
      grantorfname,
      grantorffname,
      grantorfrelation,
      id,
      grantorfmobile;
  double sanctionlimit,
      installmentno,
      servicecharge,
      installmentamount,
      serviceamount;
  DateTime sanctiondate;
  int sl;

  LoanSanction(
      {required this.somiteename,
      required this.somiteeid,
        required this.loanpurpose,
      required this.membername,
      required this.memberid,
      required this.memberphone,
      required this.installmentfrequency,
      required this.loanperiod,
      required this.remarks,
      required this.status,
      required this.grantor1name,
      required this.grantor2name,
      required this.grantor1id,
      required this.grantor2id,
      required this.grantorfname,
      required this.grantorffname,
      required this.grantorfrelation,
      required this.id,
      required this.grantorfmobile,
      required this.sanctionlimit,
      required this.servicecharge,
      required this.installmentno,
      required this.installmentamount,
      required this.serviceamount,
      required this.sanctiondate,
      required this.sl});

  Map toJson() => {
        'Somitee Name': somiteename,
        'Somitee ID': somiteeid,
        'Member Name': membername,
        'Member ID': memberid,
        'Member Phone': memberphone,
        "Sanction Limit": sanctionlimit,
        "Installment Frequency": installmentfrequency,
        "Sanction Date": sanctiondate,
        "Loan Period": loanperiod,
        "Service Charge": servicecharge,
        "Installment No": installmentno,
        "Installment Amount": installmentamount,
        "Remarks": remarks,
        "Service Amount": serviceamount,
        'Grantor 1 Name': grantor1name,
        'Grantor 1 ID': grantor1id,
        'Grantor 2 Name': grantor2name,
        'Grantor 2 ID': grantor2id,
        "Grantor F Name": grantorfname,
        "Status": status,
        'ID': id,"Loan Purpose":loanpurpose,
        "Grantor F FatherName": grantorffname,
        "Grantor F Relation": grantorfrelation,
        "Grantor F Mobile": grantorfmobile,
        'sl': sl
      };
  bool filterFn(String query) {
    return
        id.toLowerCase().contains(query.toLowerCase());
  }
  factory LoanSanction.fromJson(Map<String, dynamic> json) {
    return LoanSanction(
        somiteename: json['Somitee Name'],
        somiteeid: json['Somitee ID'],loanpurpose:json['Loan Purpose'],
        membername: json['Member Name'],
        memberid: json['Member ID'],
        memberphone: json['Member Phone'],
        sanctionlimit: json["Sanction Limit"],
        installmentfrequency: json["Installment Frequency"],
        sanctiondate: json["Sanction Date"],
        loanperiod: json["Loan Period"],
        servicecharge: json["Service Charge"],
        installmentno: json["Installment No"],
        installmentamount: json["Installment Amount"],
        remarks: json["Remarks"],
        serviceamount: json["Service Amount"],
        grantor1name: json['Grantor 1 Name'],
        grantor1id: json['Grantor 1 ID'],
        grantor2name: json['Grantor 2 Name'],
        grantor2id: json['Grantor 2 ID'],
        grantorfname: json["Grantor F Name"],
        status: json["Status"],
        id: json['ID'],
        grantorffname: json["Grantor F FatherName"],
        grantorfrelation: json["Grantor F Relation"],
        grantorfmobile: json["Grantor F Mobile"],
        sl: json['sl']);
  }
}
