class loanSanction {
  String somiteename,
      somiteeid,
      membername,
      memberid,
      memberphone,
      installmentfrequency,
      scheme,
      category,
      remarks,
      status,
      loanpurpose,
      id,
      grantorfname,
      grantorffname,
      grantorfrelation,
      grantorfocupasion,
      grantorfmobile,
      grantorsname,
      grantorsfname,
      grantorsrelation,
      grantorsocupasion,
      grantorsmobile,
      grantorpname,
      grantorpfname,
      requestedby,
      approvedby,
      grantorprelation,
      grantorpocupasion,
      grantorpmobile;
  double sanctionlimit,
      installmentno,
      servicecharge,
      installmentamount,
      serviceamount;
  DateTime sanctiondate, approvedate;
  int sl;

  loanSanction(
      {required this.somiteename,
      required this.somiteeid,
      required this.loanpurpose,
      required this.membername,
      required this.memberid,
      required this.approvedate,
      required this.memberphone,
      required this.installmentfrequency,
      required this.scheme,
      required this.category,
      required this.remarks,
      required this.status,
      required this.id,
      required this.sanctionlimit,
      required this.servicecharge,
      required this.installmentno,
      required this.installmentamount,
      required this.serviceamount,
      required this.sanctiondate,
      required this.sl,
      required this.grantorfname,
      required this.grantorffname,
      required this.grantorfrelation,
      required this.grantorfocupasion,
      required this.grantorfmobile,
      required this.grantorsname,
      required this.grantorsfname,
      required this.grantorsrelation,
      required this.grantorsocupasion,
      required this.grantorsmobile,
      required this.requestedby,
      required this.approvedby,
      required this.grantorpname,
      required this.grantorpfname,
      required this.grantorprelation,
      required this.grantorpocupasion,
      required this.grantorpmobile});

  Map toJson() => {
        'Somitee Name': somiteename,
        'Somitee ID': somiteeid,
        'Member Name': membername,
        'Member ID': memberid,
        'Member Phone': memberphone,
        "Sanction Limit": sanctionlimit,
        "Installment Frequency": installmentfrequency,
        "Sanction Date": sanctiondate,
        "Loan Scheme": scheme,
        "Approve Date": approvedate,
        'Loan Category': category,
        "Service Charge": servicecharge,
        "Installment No": installmentno,
        "Installment Amount": installmentamount,
        "Remarks": remarks,
        "Service Amount": serviceamount,
        "Status": status,
        'ID': id,
        "Loan Purpose": loanpurpose,
        "Grantor F Name": grantorfname,
        "Grantor F FatherName": grantorffname,
        "Grantor F Relation": grantorfrelation,
        "Grantor F Mobile": grantorfmobile,
        "Grantor F Occupation": grantorfocupasion,
        "Grantor S Name": grantorsname,
        "Grantor S FatherName": grantorsfname,
        "Grantor S Relation": grantorsrelation,
        "Grantor S Mobile": grantorsmobile,
        "Grantor S Occupation": grantorsocupasion,
        "Grantor P Name": grantorpname,
        "Grantor P FatherName": grantorpfname,
        "Grantor P Relation": grantorprelation,
        "Grantor P Mobile": grantorpmobile,
        "Grantor P Occupation": grantorpocupasion,
        'sl': sl
      };
  bool filterFn(String query) {
    return id.toLowerCase().contains(query.toLowerCase());
  }
  factory loanSanction.fromJson(Map<String, dynamic> json) {
    return loanSanction(
      somiteename: json['Somitee Name'] ?? '',
      somiteeid: json['Somitee ID'] ?? '',
      loanpurpose: json['Loan Purpose'] ?? '',
      membername: json['Member Name'] ?? '',
      memberid: json['Member ID'] ?? '',
      memberphone: json['Member Phone'] ?? '',
      sanctionlimit: json["Sanction Limit"] ?? 0,
      installmentfrequency: json["Installment Frequency"] ?? '',
      sanctiondate: json["Sanction Date"] != null ? json["Sanction Date"].toDate() : DateTime.now(),
      scheme: json["Loan Scheme"] ?? '',
      approvedate: json["Approve Date"] != null ? json["Approve Date"].toDate() : DateTime.now(),
      category: json['Loan Category'] ?? '',
      servicecharge: json["Service Charge"] ?? 0,
      installmentno: json["Installment No"] ?? 0,
      installmentamount: json["Installment Amount"] ?? 0,
      remarks: json["Remarks"] ?? '',
      approvedby: json["Approved By"] ?? '',
      requestedby: json["Requested By"] ?? '',
      serviceamount: json["Service Amount"] ?? 0,
      status: json["Status"] ?? '',
      id: json['ID'] ?? '',
      grantorfname: json["Grantor F Name"] ?? '',
      grantorffname: json["Grantor F FatherName"] ?? '',
      grantorfrelation: json["Grantor F Relation"] ?? '',
      grantorfmobile: json["Grantor F Mobile"] ?? '',
      grantorfocupasion: json["Grantor F Occupation"] ?? '',
      grantorsname: json["Grantor S Name"] ?? '',
      grantorsfname: json["Grantor S FatherName"] ?? '',
      grantorsrelation: json["Grantor S Relation"] ?? '',
      grantorsmobile: json["Grantor S Mobile"] ?? '',
      grantorsocupasion: json["Grantor S Occupation"] ?? '',
      grantorpname: json["Grantor P Name"] ?? '',
      grantorpfname: json["Grantor P FatherName"] ?? '',
      grantorprelation: json["Grantor P Relation"] ?? '',
      grantorpmobile: json["Grantor P Mobile"] ?? '',
      grantorpocupasion: json["Grantor P Occupation"] ?? '',
      sl: json['sl'] ?? 0,
    );
  }
}
