class Memberss {
  String somiteename,
      somiteeid,
      membertype,
      occupation,
      firstname,
      lastname,
      fathername,
      mothername,
      gender,
      religion,
      nationalid,
      birthregi,
      age,
      nodepenndent,
      education,
      maritalstatus,
      mobilenotype,
      mobilenno,
      presentadd,
      parmaadd,
      livingperiod,
      nomaleearner,
      nofemaleearner,
      id,
      headfamily,
      ownhomestead,
      relationwithhead,
      landdesc,
      housedesc,
      remarks,
      imageurl;
  bool img;
  DateTime birthdate;
  int sl;

  Memberss(
      {required this.somiteename,
      required this.somiteeid,
      required this.membertype,
      required this.occupation,
      required this.firstname,
      required this.lastname,
      required this.fathername,
      required this.mothername,
      required this.gender,
      required this.religion,
      required this.nationalid,
      required this.birthregi,
      required this.age,
      required this.nodepenndent,
      required this.education,
      required this.maritalstatus,
      required this.mobilenotype,
      required this.mobilenno,
      required this.presentadd,
      required this.parmaadd,
      required this.livingperiod,
      required this.nomaleearner,
      required this.nofemaleearner,
      required this.id,
      required this.headfamily,
      required this.ownhomestead,
      required this.relationwithhead,
      required this.landdesc,
      required this.housedesc,
      required this.remarks,
      required this.imageurl,
      required this.img,
      required this.birthdate,
      required this.sl});
}
